[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false
idl-build = ["anchor-spl/idl-build"]

[programs.localnet]
spl_gov_micro = "G3oRp71dn6S5TRmhXWXaURzGTtk485zSdZ6Xy46JkRDR"

[programs.devnet]
spl_gov_micro = "G3oRp71dn6S5TRmhXWXaURzGTtk485zSdZ6Xy46JkRDR"

[programs.mainnet]
spl_gov_micro = "G3oRp71dn6S5TRmhXWXaURzGTtk485zSdZ6Xy46JkRDR"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Devnet"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

# SPL Account Compression for zkCompression
# Note: SPL Account Compression is already available on localnet/devnet
# No need to load it in genesis for testing

# Light Protocol programs (optional, for future enhanced compression)
# Uncomment when Light Protocol programs are available locally
# [[test.genesis]]
# address = "SySTEM1eSU2p4BGQfQpimFEWWSC1XDFeun3Nqzz3rT7"
# program = "light_system_program.so"

# [[test.genesis]]
# address = "cTokenmWW8bLPjZEBAUgYy3zKxQZW6VKi7bqNFEVv3m"
# program = "light_compressed_token.so"
